
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/cache@v2

    - name: Login to Docker Hub
      env:
        USERNAME: ssinad
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push images
      env:
        USERNAME: ssinad
      run: |
        for dir in *; do 
          # echo $dir
          docker build -t $USERNAME/$dir:$GITHUB_SHA -t $USERNAME/$dir:latest $dir
          docker push $USERNAME/$dir:$GITHUB_SHA
          docker push $USERNAME/$dir:latest
        done
