
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/cache@v2

    # - name: Login to GitLab
    #   uses: docker/login-action@v1
    #   with:
    #     registry: registry.gitlab.com
    #     username: ${{ secrets.GITLAB_USERNAME }}
    #     password: ${{ secrets.GITLAB_PASSWORD }}

    - name: Build images
      run: |
        for dir in ./*; do 
          echo $dir
          docker build -t registry.gitlab.com/${{ secrets.GITLAB_USERNAME }}/$dir:github $dir
        done
