
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  USERNAME: ssinad

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/cache@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push images
      # env:
      #   USERNAME: ${{ env.USERNAME }}
      run: |
        for dir in *; do 
          TAGS="-t $USERNAME/$dir:$GITHUB_SHA -t $USERNAME/$dir:latest"
          ./github/scripts/docker-build-push.sh $USERNAME "$dir" "$TAGS" $GITHUB_SHA &
        done
        wait
