
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/cache@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push images
      run: |
        for dir in *; do 
          # echo $dir
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/$dir:latest $dir
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$dir:latest
        done
